os:
  - linux
  - osx
language: node_js
node_js:
  - "node"
  - "8"
cache:
  directories:
    - "node_modules"
env:
  - HUSKY_DEBUG=1
script:
  - which time
  - sh ./scripts/test-install.sh
  - npm test
